config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  resources :meetings
  root 'landing#index'
  devise_for :usuarios, controllers: {registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    layout :changeLayout

    private 
        def changeLayout
            if devise_controller?
                "login"
            else
                "application"
            end
        end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_usuario! 
  layout 'dashboard'
  def index
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :authenticate_usuario!
  layout 'dashboard'

  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:dni, :name, :lastname, :email, :cel, :date, :status)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController    
    private

    def sign_up_params
        params.require(:usuario).permit(:dni, :name, :lastname, :email, :password, :password_confirmation)

    end

    def account_update_params
        params.require(:usuario).permit(:dni, :name, :lastname, :email, :password, :password_confirmation, :current_password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/dashboard/index.html.erb
<!-- HEADER -->
<div class="page-header light-fg row no-gutters align-items-center justify-content-between">

    <!-- APP TITLE -->
    <div class="col-12 col-sm">

        <div class="logo row no-gutters justify-content-center align-items-start justify-content-sm-start">
            <div class="logo-icon mr-3 mt-1">
                <i class="icon-cube-outline s-6"></i>
            </div>
            <div class="logo-text">
                <div class="h4">Products</div>
                <div class="">Total Products: 20</div>
            </div>
        </div>

    </div>
    <!-- / APP TITLE -->

    <!-- SEARCH -->
    <div class="col search-wrapper px-2">

        <div class="input-group">
            <span class="input-group-btn">
                <button type="button" class="btn btn-icon">
                    <i class="icon icon-magnify"></i>
                </button>
            </span>
            <input id="products-search-input" type="text" class="form-control" placeholder="Search" aria-label="Search" />
        </div>

    </div>
    <!-- / SEARCH -->

    <div class="col-auto">
        <a href="apps-e-commerce-product.html" class="btn btn-light">ADD NEW PRODUCT</a>
    </div>

</div>
<!-- / HEADER -->

app/views/landing/index.html.erb
<h1>Landing#index</h1>
<p>Find me in app/views/landing/index.html.erb</p>

<%= link_to 'Dashboard', dashboard_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppFantom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppFantom - Dashboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="layout layout-vertical layout-left-navigation layout-below-toolbar layout-below-footer">

    <main> 
      <div id="wrapper">
        <aside class="aside aside-left" id="aside" data-fuse-bar="aside" data-fuse-bar-media-step="md" data-fuse-bar-position="left">
          <div class="aside-content bg-primary-700 text-auto">
            <div class="aside-toolbar">
              <div class="logo"><span class="logo-icon">F</span><span class="logo-text">Fantom</span></div>
              <button class="btn btn-icon d-none d-lg-block" id="toggle-fold-aside-button" type="button" data-fuse-aside-toggle-fold><i class="icon icon-backburger"></i></button>
            </div>
            <ul class="nav flex-column custom-scrollbar" id="sidenav" data-children=".nav-item">
              <li class="subheader"><span>FANTOM</span></li>
              
              <li class="nav-item"><a class="nav-link ripple active" href="#" data-url="index.html">
                  <div class="icon s-4 icon-calendar-today"></div><span>Citas</span></a></li>

              <li class="nav-item" id="heading-dashboards" role="tab"><a class="nav-link ripple with-arrow collapsed" href="" data-toggle="collapse" data-target="#collapse-dashboards" aria-expanded="false" aria-controls="collapse-dashboards"><i class="icons s-4 icon-title-four"></i><span>Dashboards</span></a>
                <ul class="collapse show" id="collapse-dashboards" role="tabpanel" aria-labelledby="heading-dashboards" data-children=".nav-item">
                  <li class="nav-item"><a class="nav-link ripple" href="#" data-url="index.html"><span>Dashboard</span></a></li>
                  <li class="nav-item"><a class="nav-link ripple" href="#" data-url="index.html"><span>Citas </span></a></li>
                </ul>
              </li>
              
            </ul>
          </div>
        </aside>
        <div class="content-wrapper">
          <nav class="bg-white" id="toolbar">
            <div class="row no-gutters align-items-center flex-nowrap">
              <div class="col">
                <div class="row no-gutters align-items-center flex-nowrap">
                  <button class="toggle-aside-button btn btn-icon d-block d-lg-none" type="button" data-fuse-bar-toggle="aside"><i class="icon icon-menu"></i></button>
                  <div class="toolbar-separator d-block d-lg-none"></div>
                </div>
              </div>
              <div class="col-auto">
                <div class="row no-gutters align-items-center justify-content-end">
                  <div class="user-menu-button dropdown">
                  
       
   
                    <div class="dropdown-toggle ripple row align-items-center no-gutters px-2 px-sm-4" role="button" id="dropdownUserMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <div class="avatar-wrapper"><img class="avatar" src="./assets/img/avatars/profile.jpg" alt="Avatar"><i class="status text-green icon-checkbox-marked-circle s-4"></i></div>
                      <span class="username mx-3 d-none d-md-block"><% if usuario_signed_in? %> <%= current_usuario.name %>  <%= current_usuario.lastname %><% end %></span>
                    </div>
                    
                    <div class="dropdown-menu" aria-labelledby="dropdownUserMenu">
                        <a class="dropdown-item" href="">
                            <div class="row no-gutters align-items-center flex-nowrap">
                                <div class="icon-account"></div>
                                <span class="px-3">Perfil</span>
                            </div>
                        </a>
                        <% if usuario_signed_in? %>
                            <%= link_to ('<div class="row no-gutters align-items-center flex-nowrap"><div class="icon-logout"></div><span class="px-3">Cerrar Sesión</span></div>').html_safe, destroy_usuario_session_path, :method => 'delete', class:"dropdown-item" %>
                        <% end %>                        
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </nav>
          <div class="content custom-scrollbar">
            <div id="e-commerce-products" class="page-layout carded full-width">
                <div class="top-bg bg-primary"></div>
                 <!-- CONTENT -->
                 <div class="page-content-wrapper">
                    <!-- Para el header y el content son dinámicos-->
                    <%= yield %>
                 </div>
                 <!-- / CONTENT -->

            </div>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inmobiliaria Fantom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inmobiliaria Fantom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="layout layout-vertical layout-left-navigation layout-below-toolbar layout-below-footer">
    <%= yield %>
  </body>
</html>

app/views/meetings/_form.html.erb
<%= form_with(model: meeting, local: true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :dni %>
    <%= form.number_field :dni %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :cel %>
    <%= form.text_field :cel %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<!-- HEADER -->
<div class="page-header light-fg row no-gutters align-items-center justify-content-between">

    <!-- APP TITLE -->
    <div class="col-12 col-sm">

        <div class="logo row no-gutters justify-content-center align-items-start justify-content-sm-start">
            <div class="logo-icon mr-3 mt-1">
                <i class="icon-cube-outline s-6"></i>
            </div>
            <div class="logo-text">
                <div class="h4">Citas</div>
                <div class="">Total de citas: 20</div>
            </div>
        </div>

    </div>
    <!-- / APP TITLE -->

    <!-- SEARCH -->
    <div class="col search-wrapper px-2">

        <div class="input-group">
            <span class="input-group-btn">
                <button type="button" class="btn btn-icon">
                    <i class="icon icon-magnify"></i>
                </button>
            </span>
            <input id="products-search-input" type="text" class="form-control" placeholder="Search" aria-label="Search" />
        </div>

    </div>
    <!-- / SEARCH -->

    <div class="col-auto">        
        <%= link_to 'Nueva cita', new_meeting_path, class:"btn btn-light" %>
    </div>

</div>
<!-- / HEADER -->
<div class="page-content-card">
    <table id="e-commerce-products-table" class="table dataTable">
        <thead>
            <tr>
                <th>
                    <div class="table-header">
                        <span class="column-title">ID</span>
                    </div>
                </th>

                <th>
                    <div class="table-header">
                        <span class="column-title">Dni</span>
                    </div>
                </th>

                <th>
                    <div class="table-header">
                        <span class="column-title">Nombre</span>
                    </div>
                </th>

                <th>
                    <div class="table-header">
                        <span class="column-title">Correo</span>
                    </div>
                </th>

                <th>
                    <div class="table-header">
                        <span class="column-title">Celular</span>
                    </div>
                </th>

                <th>
                    <div class="table-header">
                        <span class="column-title">Fecha de cita</span>
                    </div>
                </th>

                <th>
                    <div class="table-header">
                        <span class="column-title">Estado</span>
                    </div>
                </th>

                <th colspan="3">
                    <div class="table-header">
                        <span class="column-title">Actions</span>
                    </div>
                </th>
            </tr>
        </thead>

        <tbody>
          <% @meetings.each do |meeting| %>

            <tr>
                <td><%= meeting.id %></td>               
                <td><%= meeting.dni %></td>
                <td><%= meeting.name %> <%= meeting.lastname %></td>
                <td><%= meeting.email %></td>
                <td><%= meeting.cel %></td>
                <td><%= meeting.date %></td>
                <td><%= meeting.status %></td>
                <td><%= link_to 'Show', meeting %></td>
                <td><%= link_to ('<i class="icon icon-pencil s-4"></i>').html_safe, edit_meeting_path(meeting), class:"btn btn-icon" %></td>
                <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                
            </tr>


          <% end %>
        </tbody>
    </table>
</div>

<p id="notice"><%= notice %></p>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dni:</strong>
  <%= @meeting.dni %>
</p>

<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @meeting.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @meeting.email %>
</p>

<p>
  <strong>Cel:</strong>
  <%= @meeting.cel %>
</p>

<p>
  <strong>Date:</strong>
  <%= @meeting.date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @meeting.status %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>